# Generated by Django 6.0.2 on 2026-02-17 09:34

import ckeditor_uploader.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL (Slug)')),
                ('summary', models.TextField(max_length=500, verbose_name='Résumé pour SEO')),
                ('category', models.CharField(blank=True, choices=[('tutorial', 'Tutoriel'), ('news', 'Actualité'), ('devops', 'DevOps')], max_length=50)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Contenu')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Image de couverture')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de publication')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles de blog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de réception')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('is_responded', models.BooleanField(default=False, verbose_name='Répondu')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du projet')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(verbose_name='Description courte')),
                ('image', models.ImageField(upload_to='portfolio/', verbose_name='Image de présentation')),
                ('url', models.URLField(blank=True, verbose_name='Lien vers le site (Live)')),
                ('github_url', models.URLField(blank=True, verbose_name='Lien GitHub (Optionnel)')),
                ('technologies', models.CharField(help_text='Séparez par des virgules (ex: Django, Tailwind, Docker)', max_length=200)),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date de réalisation')),
                ('is_featured', models.BooleanField(default=False, verbose_name="Afficher sur l'accueil ?")),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Portfolio',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse email')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='Prénom')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Nom')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Photo de profil')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('manager', 'Manager'), ('client', 'Client'), ('staff', 'Staff')], default='client', max_length=20, verbose_name='Rôle')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Accès admin')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'inscription")),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-date_joined'],
            },
        ),
    ]
