# Generated by Django 6.0.2 on 2026-02-20 14:45

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('mentions-legales', 'Mentions Légales'), ('confidentialite', 'Politique de Confidentialité'), ('cookies', 'Politique des Cookies')], max_length=200, unique=True, verbose_name='Type de page')),
                ('slug', models.SlugField(help_text='Ex: mentions-legales', unique=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Contenu de la page')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
            ],
            options={
                'verbose_name': 'Page Légale',
                'verbose_name_plural': 'Pages Légales',
            },
        ),
    ]
