# Generated by Django 6.0.2 on 2026-02-21 13:42

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_legalpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='WEBP', keep_meta=True, null=True, quality=85, scale=None, size=[1200, 675], upload_to='blog/', verbose_name='Image de couverture'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=85, scale=None, size=[400, 400], upload_to='avatars/', verbose_name='Photo de profil'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=85, scale=None, size=[1200, 900], upload_to='portfolio/', verbose_name='Image de présentation'),
        ),
    ]
