# Generated by Django 6.0.8 on 2026-10-03 11:37

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_article_updated_at_project_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Contenu de la page'),
        ),
    ]
